# src/cscie103_olap_oltp/contracts/schema.py
"""The published shape of an emitted artifact.

    Schema as Code    a committed contract, reviewed like any other file
    Evidence as Data  what execution emits conforms to it, provably

WHY THIS EXISTS ALONGSIDE THE PYDANTIC MODELS. Pydantic validates on the way IN,
inside one process. A consumer reading .artifacts/verdicts/*.json months from
now has no models -- it has JSON. Rename a field and that reader breaks while
every producer test here still passes, because nothing in this repository was
ever asked whether the OUTPUT shape held.

PYDANTIC CANNOT DO THE CHECKING EITHER. It generates JSON Schema and does
nothing to validate a schema against its metaschema, or an instance against a
schema. `jsonschema` is what makes the contract load-bearing.

THE COMMITTED BYTES ARE CANONICAL, AND THAT IS A DELIBERATE INVERSION.
The obvious design regenerates the schema on demand and compares. It has a
documented failure: a pydantic point release can subtly change generated output,
so the gate goes red for an upgrade that broke nothing -- and once people learn
to regenerate reflexively on any failure, real drift passes through unnoticed.

So the published file changes only when someone runs `mise run schema:generate`,
and artifacts are validated against THOSE bytes. The comparison gate is kept
because uv.lock pins pydantic exactly here, which makes a difference mean a
MODEL changed rather than a library did.
"""

from __future__ import annotations

import json
import sys
from typing import Any

from cscie103_olap_oltp.contracts.verdict import Decision
from cscie103_olap_oltp.policy.snapshot import REPO_ROOT

# PUBLISHED BESIDE THE OTHER CONTRACTS, not under .artifacts. This is intent,
# not evidence: it is reviewed, versioned and consumed, while .artifacts holds
# observations and is gitignored.
SCHEMA_PATH = REPO_ROOT / "contracts" / "decision.schema.json"

# THE DIALECT IS DECLARED. Without $schema a validator guesses, and dialects
# disagree about what an unknown keyword means -- silently, and in the
# permissive direction.
DIALECT = "https://json-schema.org/draft/2020-12/schema"

# THE VERSION LIVES IN THE CONTRACT NAME THE ARTIFACT ALREADY CARRIES.
# Every verdict says `repository/v1` in a field a consumer can read, so keying
# off a filename it would have to infer is unnecessary indirection.
SCHEMA_ID = "https://github.com/ltphongssvn/cscie103-olap-oltp/contracts/decision.schema.json"


def generate_schema() -> dict[str, Any]:
    """Render the schema from the models.

    DETERMINISTIC BY CONSTRUCTION: pydantic emits a stable ordering, and the
    file is written with sorted keys. A generator that reordered anything would
    make every regeneration a diff and the drift gate meaningless.

    THE TOP LEVEL IS Decision, not Verdict, because a decision is what is
    actually written to disk -- and it carries the verdict inside it.
    """
    schema = Decision.model_json_schema(mode="serialization")
    schema["$schema"] = DIALECT
    schema["$id"] = SCHEMA_ID
    schema["title"] = "Decision"
    schema["description"] = (
        "One enforcement decision: the verdict that produced it, the action "
        "taken, and when. Generated from the pydantic models -- edit those, "
        "then run `mise run schema:generate`."
    )
    return schema


def _serialise(schema: dict[str, Any]) -> str:
    """One canonical rendering, so a byte comparison is meaningful."""
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def committed_schema() -> dict[str, Any]:
    """The published contract, as consumers receive it.

    READ FROM DISK RATHER THAN REGENERATED, which is the whole point: tests
    that validate against freshly generated bytes prove only that the models
    agree with themselves.
    """
    if not SCHEMA_PATH.is_file():
        raise FileNotFoundError(f"{SCHEMA_PATH} is missing; run `mise run schema:generate`")
    parsed: dict[str, Any] = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    return parsed


def schema_matches_models() -> bool:
    """Whether the committed contract still describes the current models."""
    return SCHEMA_PATH.is_file() and SCHEMA_PATH.read_text(encoding="utf-8") == _serialise(
        generate_schema()
    )


def main() -> int:
    """Generate or check, and say which.

    TWO VERBS, NOT ONE FLAGLESS DEFAULT. Regeneration edits a committed
    contract, so it has to be asked for explicitly -- a command that silently
    rewrote the published schema whenever a model changed would turn a
    reviewable decision into a side effect.
    """
    match sys.argv[1:]:
        case ["--generate"]:
            SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
            SCHEMA_PATH.write_text(_serialise(generate_schema()), encoding="utf-8")
            print(f"wrote {SCHEMA_PATH.relative_to(REPO_ROOT)}")
            return 0

        case ["--check"]:
            if not SCHEMA_PATH.is_file():
                print(
                    f"{SCHEMA_PATH.name} is missing; run `mise run schema:generate`",
                    file=sys.stderr,
                )
                return 1

            if not schema_matches_models():
                print(
                    f"{SCHEMA_PATH.name} no longer describes the models.\n"
                    "A field was added, renamed or retyped without regenerating.\n"
                    "Fix: mise run schema:generate",
                    file=sys.stderr,
                )
                return 1

            print(f"{SCHEMA_PATH.name} matches the models")
            return 0

        case other:
            raise SystemExit(f"usage: --generate | --check  (got {other})")


if __name__ == "__main__":
    raise SystemExit(main())
