# src/cscie103_olap_oltp/olap/ddl.py
"""Render the pipeline's dimension schemas from the contracts.

    Schema as Code      the pandera models are the one source
    Migration as Code   the DDL is generated, never typed

WHY THIS EXISTS. An IDENTITY surrogate key requires a SPECIFIED target schema,
and specifying one replaces the inferred schema entirely -- so the pipeline had
to spell out every column, duplicating the contract. Two descriptions of one
table, with nothing checking agreement, is the drift this repository gates
everywhere else.

A SINGLE SOURCE OF TRUTH STORES EVERY DATA ELEMENT EXACTLY ONCE and generates
the rest. The contract is that source; this renders the pipeline's view of it.

WHY A FILE AND NOT AN IMPORT. `dlt` exists only inside a pipeline runtime, and
the error-code registry's package walk already proved that boundary must be
physical rather than conventional. A committed, gated JSON file crosses it
without either side importing the other.
"""

from __future__ import annotations

import json
import sys
from typing import Any

import pandera.pandas as pa

from cscie103_olap_oltp.olap.contracts import TABLES, Versioned
from cscie103_olap_oltp.policy.snapshot import REPO_ROOT

__all__ = [
    "SCD2_COLUMNS",
    "SCHEMAS_PATH",
    "generate",
    "is_versioned",
    "matches_models",
    "streaming_table_schema",
]

SCHEMAS_PATH = REPO_ROOT / "contracts" / "olap.streaming-tables.json"

# LAKEFLOW'S VOCABULARY FOR THE VALIDITY INTERVAL.
#
# Databricks requires these in a specified SCD Type 2 target schema, typed like
# the sequencing column. They are the framework's names for what the pandera
# contract calls valid_from and valid_to.
SCD2_COLUMNS = ("__START_AT", "__END_AT")

# THE CONTRACT'S NAMES FOR WHAT THE FRAMEWORK SUPPLIES.
#
# A dimension contract describes the table a READER sees -- valid_from,
# valid_to, is_current. AUTO CDC produces that history itself, so declaring
# those columns in the target would collide with the ones it maintains.
FRAMEWORK_OWNED = frozenset({"valid_from", "valid_to", "is_current"})

# THE SURROGATE KEY SUFFIX. A dimension's key column is <entity>_key by
# convention here, and that convention is what lets the key be identified
# rather than configured per table.
KEY_SUFFIX = "_key"

SQL_TYPES = {
    "int64": "BIGINT",
    "float64": "DOUBLE",
    "bool": "BOOLEAN",
    "string[python]": "STRING",
    "datetime64[ns]": "TIMESTAMP",
}


def _columns(name: str, schema: pa.DataFrameSchema) -> list[str]:
    """The declared columns, in contract order, with the key made generated."""
    rendered: list[str] = []

    for column, spec in schema.columns.items():
        if column in FRAMEWORK_OWNED:
            continue

        dtype = str(spec.dtype)
        if dtype not in SQL_TYPES:
            raise SystemExit(
                f"no SQL type mapped for pandera dtype {dtype!r} (column {column!r}) "
                f"in {name}; add it to SQL_TYPES"
            )

        if column.endswith(KEY_SUFFIX) and column.removesuffix(KEY_SUFFIX) in name:
            # THE SURROGATE KEY, GENERATED BY THE PIPELINE. Declaring it as an
            # ordinary BIGINT would make the contract's key a column the loader
            # never fills, and every fact join would resolve to the Unknown
            # member without anything reporting an error.
            rendered.append(f"{column} BIGINT GENERATED ALWAYS AS IDENTITY")
            continue

        rendered.append(f"{column} {SQL_TYPES[dtype]}")

    # THE SEQUENCING COLUMN, WHICH THE CONTRACT DELIBERATELY OMITS. It is
    # warehouse plumbing rather than a business fact -- see oltp/tables.py --
    # but AUTO CDC orders changes by it, so the target must hold it.
    rendered.append("updated_at TIMESTAMP")
    rendered.extend(f"{column} TIMESTAMP" for column in SCD2_COLUMNS)

    return rendered


def is_versioned(model: type[pa.DataFrameModel]) -> bool:
    """Whether AUTO CDC maintains this table's history.

    THE MODEL DECLARES IT by inheriting Versioned. Asking the type is a question
    with one answer; sniffing for validity columns infers a capability from its
    symptoms, and a `dim_` prefix infers it from spelling -- which swept in
    dim_date, a conformed calendar with no history because a date never changes.
    """
    return issubclass(model, Versioned)


def generate() -> dict[str, str]:
    """One schema string per VERSIONED dimension.

    FACTS AND CALENDARS ARE ABSENT BY CONSTRUCTION. A fact is the result of a
    query and a calendar has no versions, so neither is a table AUTO CDC
    maintains -- declaring a schema for either would freeze a shape nothing
    will fill.
    """
    return {
        name: ",\n".join(_columns(name, model.to_schema()))
        for name, model in sorted(TABLES.items())
        if is_versioned(model)
    }


def streaming_table_schema(name: str) -> str:
    """The schema for one dimension. RAISES for anything that is not one."""
    return generate()[name]


def _serialise(document: dict[str, Any]) -> str:
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def matches_models() -> bool:
    return SCHEMAS_PATH.is_file() and SCHEMAS_PATH.read_text(encoding="utf-8") == _serialise(
        generate()
    )


def main() -> int:
    match sys.argv[1:]:
        case ["--generate"]:
            SCHEMAS_PATH.parent.mkdir(parents=True, exist_ok=True)
            SCHEMAS_PATH.write_text(_serialise(generate()), encoding="utf-8")
            print(f"wrote {SCHEMAS_PATH.relative_to(REPO_ROOT)}")
            return 0

        case ["--check"]:
            if not matches_models():
                print(
                    f"{SCHEMAS_PATH.name} no longer matches the dimension contracts.\n"
                    "Fix: mise run contracts:generate",
                    file=sys.stderr,
                )
                return 1
            print(f"{SCHEMAS_PATH.name} matches the dimension contracts")
            return 0

        case other:
            raise SystemExit(f"usage: --generate | --check  (got {other})")


if __name__ == "__main__":
    raise SystemExit(main())
